---
- name: コンテナを再起動
  ansible.builtin.command:
    cmd: /usr/local/bin/docker-compose restart
    chdir: "{{ training_dir }}/containers"
  environment:
    DOCKER_HOST: "unix:///run/podman/podman.sock"
