FROM registry.access.redhat.com/ubi10/ubi-init

RUN dnf -y install openssh-server openssh-clients sudo python3 python3-pip \
    gcc make curl tar ncurses vim-minimal && \
    dnf clean all

RUN curl -LO https://sourceforge.net/projects/sshpass/files/sshpass/1.10/sshpass-1.10.tar.gz && \
    tar xzf sshpass-1.10.tar.gz && \
    cd sshpass-1.10 && ./configure && make && make install && \
    cd / && rm -rf sshpass-1.10 sshpass-1.10.tar.gz

RUN ssh-keygen -A && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    echo 'root:password' | chpasswd && \
    systemctl enable sshd

RUN pip3 install ansible pywinrm jmespath ansible-lint

RUN echo 'infocmp "$TERM" &>/dev/null || export TERM=xterm-256color' >> /root/.bashrc

ENV ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3
ENV ANSIBLE_INJECT_FACT_VARS=True

EXPOSE 22

CMD ["/sbin/init"]
