---
- name: ローカルリポジトリサーバーセットアップ
  ansible.builtin.import_playbook: repo-server-setup.yml

- name: Airgap 研修環境セットアップ（RHEL）
  ansible.builtin.import_playbook: rhel-setup.yml

- name: Windows クライアントセットアップ
  ansible.builtin.import_playbook: windows-client-setup.yml
